# Generated by Django 4.2.25 on 2025-10-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emp', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=25)),
                ('nroDoc', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=11)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pro', models.CharField(max_length=30)),
                ('rut_pro', models.CharField(max_length=10)),
                ('telefono_pro', models.IntegerField(max_length=11)),
                ('direccion_pro', models.CharField(max_length=40)),
            ],
        ),
    ]
