# Generated by Django 5.2.7 on 2025-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_empleado_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='correo_pro',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio_fiscal_pro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion_pro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_pro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_pro',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_pro',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
