# Generated by Django 5.2.8 on 2025-11-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_alter_producto_precio_alter_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexentry',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
